# Enable mouse emulation.
# CONFIG_ZMK_POINTING=y

# Idle after 30s (default)
CONFIG_ZMK_IDLE_TIMEOUT=30000

# Deep sleep after 10 minutes of idle (saves battery)
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=600000

# Custom keyboard name (max. 16 characters)
# CONFIG_ZMK_KEYBOARD_NAME="My Keyboard"

CONFIG_ZMK_RGB_UNDERGLOW_ON_START=n
